version: "3.9"
services:
  db:
    image: postgres:14.8-alpine3.18
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .db.env
    ports:
      - "5432:5432"
    networks:
      - app-network # Добавлено подключение к сети  
  web:

    build: ./app
    volumes:
      - ./app/:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - app-network # Добавлено подключение к сети

  ui:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - web
    environment:
      - VITE_API_URL=http://localhost:8000/api
    networks:
      - app-network # Добавлено подключение к сети  

volumes:
  db-data:


networks:
  app-network:
    driver: bridge


