version: "3.9"
services:
  web:
    build: ./app
    volumes:
      - ./app/:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  db:
    image: postgres:14.8-alpine3.18
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .db.env
    ports:
      - "5432:5432"
  ui:
    build: ./frontend
    
    ports:
      - "80:80"
    
    depends_on:
      - web
    environment:
      - VITE_API_URL=http://localhost:8000/api

volumes:
  db-data:


